config/routes.rb
Rails.application.routes.draw do
  resources :todos
  devise_for :users
  root 'todos#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :content, :presence => true
  validates :user, :presence => true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone_number
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name

    devise_parameter_sanitizer.for(:account_update) << :phone_number
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo, :only => [:edit, :update, :destroy, :show]

  before_action :ensure_current_user_is_todo_owner, :only => [:edit, :update, :destroy]

  def ensure_current_user_is_todo_owner
    if current_user != @todo.user
      redirect_to root_url, :notice => "Nice try, buddy"
    end
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def index
    @todos = current_user.todos

    respond_to do |format|
      format.html
      format.json { render :json => @todos }
    end
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user

    if @todo.save
      redirect_to todos_url, :notice => "Todo created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def todo_params
    return params.require(:todo).permit(:content, :new_column)
  end

  def update
    @todo.update_attributes(todo_params)

    # @todo.content = params[:todo][:content]
    # @todo.user_id = params[:todo][:user_id]

    if @todo.save
      redirect_to todo_url(@todo.id), :notice => "Todo updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @todo.destroy

    redirect_to todos_url, :notice => "Todo deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MyTodos</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/superhero/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">MyTodos</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/todos">Todos</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user != nil %>
          <li><a href="/users/edit"><%= current_user.email %></a></li>
          <li><a href="/users/sign_out" data-method="delete">Sign out</a></li>
        <% else %>
          <li><a href="/users/sign_up">Sign up</a></li>
          <li><a href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.text_field :new_content %>

  <%= f.submit %>
<% end %>

app/views/todos/_todo.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Todo #<%= todo.id %></h3>
    </div>
    <div class="panel-body">
      <dl>
        <dt>Content</dt>
        <dd><%= todo.content %></dd>
      </dl>
      <div class="btn-group btn-group-justified">
        <%= link_to todo_url(todo), :class => "btn btn-primary" do %>
          <i class="fa fa-search-plus"></i>
        <% end %>
        <% if todo.user == current_user %>
          <%= link_to edit_todo_url(todo), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to todo_url(todo), :method => "delete", :data => { :confirm => "Do you really want to delete this todo?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todos/edit.html.erb
<p>Edit form</p>

<%= render 'form' %>

app/views/todos/index.html.erb
<div class="page-header">
  <h1>
    Todos
    <%= link_to new_todo_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>


<% if current_user.present? %>
<div class="row">
  <div class="col-xs-12">
    <%= form_tag "/todos"  do%>
      <input name="content" type="text" class="form-control" placeholder="Add a new todo">
      <input name="user_id" type="hidden" value="<%= current_user.id %>">
    <% end %>
  </div>
</div>

<hr>
<% end %>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Todos (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
  <%= render @todos %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/todos/new.html.erb
<p>New Form</p>

<%= render 'form' %>

app/views/todos/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <%= render @todo %>
</div>

<!-- End responsive panel example -->